#!/usr/bin/env node
/**
 * ---------------------------------------------------------------------------
 * RESPONSIVE IMAGE PIPELINE
 * ---------------------------------------------------------------------------
 * Reads every source photograph in public/images, writes re-encoded WebP
 * variants at the breakpoints the layout actually uses, and regenerates
 * src/data/imageManifest.ts so <SmartImage /> can emit a correct `srcset`.
 *
 * Usage:
 *   npm run images
 *
 * Notes:
 * - Originals are never modified or deleted; they stay as the `src` fallback.
 * - Re-runs are incremental: a variant is only rebuilt when its source is newer.
 * - TODO: when real Bandhan Events photography replaces the placeholders, drop
 *   the new files into public/images and re-run `npm run images`.
 */

import { readdir, stat, writeFile, mkdir } from "node:fs/promises";
import { existsSync } from "node:fs";
import path from "node:path";
import { fileURLToPath } from "node:url";
import sharp from "sharp";

const root = path.resolve(path.dirname(fileURLToPath(import.meta.url)), "..");
const imagesDir = path.join(root, "public", "images");
const manifestPath = path.join(root, "src", "data", "imageManifest.ts");

/**
 * Viewport-driven breakpoints — matches the widths the layout actually uses.
 * The untouched original is always offered at its native width by the
 * consumer's srcset, so no near-duplicate top-end variant is generated.
 */
const WIDTHS = [480, 800, 1200];
const QUALITY = 72;
const SOURCE_EXTENSIONS = new Set([".webp", ".jpg", ".jpeg", ".png"]);
/** Files produced by this script: `<base>-<width>.webp` where width is a known breakpoint. */
const VARIANT_PATTERN = /-(\d+)\.webp$/;

const isGeneratedVariant = (name) => {
  const match = VARIANT_PATTERN.exec(name);
  return match ? WIDTHS.includes(Number(match[1])) : false;
};

const toPosix = (p) => p.split(path.sep).join("/");

async function isStale(source, target) {
  if (!existsSync(target)) return true;
  const [srcStat, outStat] = await Promise.all([stat(source), stat(target)]);
  return srcStat.mtimeMs > outStat.mtimeMs;
}

async function main() {
  await mkdir(imagesDir, { recursive: true });

  const entries = (await readdir(imagesDir)).filter((name) => {
    const ext = path.extname(name).toLowerCase();
    return SOURCE_EXTENSIONS.has(ext) && !isGeneratedVariant(name);
  });

  if (entries.length === 0) {
    console.warn("No source images found in public/images — nothing to do.");
    return;
  }

  /** @type {Record<string, { width: number, height: number, variants: { w: number, src: string }[] }>} */
  const manifest = {};
  let sourceBytes = 0;
  let generated = 0;
  let reused = 0;

  for (const name of entries.sort()) {
    const source = path.join(imagesDir, name);
    sourceBytes += (await stat(source)).size;

    const meta = await sharp(source, { failOn: "none" }).metadata();
    const originalWidth = meta.width ?? 0;

    // Only smaller-than-source widths are generated; the original covers the top end.
    const targets = WIDTHS.filter((w) => w < originalWidth).sort((a, b) => a - b);

    const variants = [];
    for (const width of targets) {
      const base = path.basename(name, path.extname(name));
      const fileName = `${base}-${width}.webp`;
      const target = path.join(imagesDir, fileName);

      if (await isStale(source, target)) {
        await sharp(source, { failOn: "none" })
          .resize({ width, withoutEnlargement: true })
          .webp({ quality: QUALITY, effort: 5, smartSubsample: true })
          .toFile(target);
        generated += 1;
      } else {
        reused += 1;
      }

      variants.push({ w: width, src: `/images/${fileName}` });
    }

    manifest[`/images/${name}`] = {
      width: originalWidth,
      height: meta.height ?? 0,
      variants,
    };
  }

  const header = `/**
 * AUTO-GENERATED by scripts/optimize-images.mjs — do not edit by hand.
 * Run \`npm run images\` after adding or replacing photography.
 *
 * Maps each source image to its re-encoded WebP variants so components can
 * build an accurate \`srcset\` without hardcoding breakpoints.
 */

import type { ImageManifest } from "@/data/images";

export const imageManifest: ImageManifest = `;

  await writeFile(
    manifestPath,
    `${header}${JSON.stringify(manifest, null, 2)} as const;\n`,
    "utf8"
  );

  console.log(
    `Images: ${entries.length} source photo(s) • variants generated ${generated}, reused ${reused} • source weight ${(
      sourceBytes / 1024 / 1024
    ).toFixed(1)} MB • manifest → ${toPosix(path.relative(root, manifestPath))}`
  );
}

main().catch((error) => {
  console.error("Image pipeline failed:", error.message);
  process.exit(1);
});
