/**
 * AUTO-GENERATED by scripts/optimize-images.mjs — do not edit by hand.
 * Run `npm run images` after adding or replacing photography.
 *
 * Maps each source image to its re-encoded WebP variants so components can
 * build an accurate `srcset` without hardcoding breakpoints.
 */

import type { ImageManifest } from "@/data/images";

export const imageManifest: ImageManifest = {
  "/images/banquet-1.webp": {
    "width": 1600,
    "height": 1067,
    "variants": [
      {
        "w": 480,
        "src": "/images/banquet-1-480.webp"
      },
      {
        "w": 800,
        "src": "/images/banquet-1-800.webp"
      },
      {
        "w": 1200,
        "src": "/images/banquet-1-1200.webp"
      }
    ]
  },
  "/images/banquet-2.webp": {
    "width": 1600,
    "height": 1067,
    "variants": [
      {
        "w": 480,
        "src": "/images/banquet-2-480.webp"
      },
      {
        "w": 800,
        "src": "/images/banquet-2-800.webp"
      },
      {
        "w": 1200,
        "src": "/images/banquet-2-1200.webp"
      }
    ]
  },
  "/images/banquet-carpet-aisle-seating.webp": {
    "width": 1200,
    "height": 675,
    "variants": [
      {
        "w": 480,
        "src": "/images/banquet-carpet-aisle-seating-480.webp"
      },
      {
        "w": 800,
        "src": "/images/banquet-carpet-aisle-seating-800.webp"
      }
    ]
  },
  "/images/banquet-entrance-drape.webp": {
    "width": 1200,
    "height": 675,
    "variants": [
      {
        "w": 480,
        "src": "/images/banquet-entrance-drape-480.webp"
      },
      {
        "w": 800,
        "src": "/images/banquet-entrance-drape-800.webp"
      }
    ]
  },
  "/images/banquet-golden-round-tables.webp": {
    "width": 1092,
    "height": 1440,
    "variants": [
      {
        "w": 480,
        "src": "/images/banquet-golden-round-tables-480.webp"
      },
      {
        "w": 800,
        "src": "/images/banquet-golden-round-tables-800.webp"
      }
    ]
  },
  "/images/banquet-golden-theatre-seating.webp": {
    "width": 1122,
    "height": 1402,
    "variants": [
      {
        "w": 480,
        "src": "/images/banquet-golden-theatre-seating-480.webp"
      },
      {
        "w": 800,
        "src": "/images/banquet-golden-theatre-seating-800.webp"
      }
    ]
  },
  "/images/banquet-luxury-buffet.webp": {
    "width": 1092,
    "height": 1440,
    "variants": [
      {
        "w": 480,
        "src": "/images/banquet-luxury-buffet-480.webp"
      },
      {
        "w": 800,
        "src": "/images/banquet-luxury-buffet-800.webp"
      }
    ]
  },
  "/images/birthday-neon-glow-crazy.webp": {
    "width": 1122,
    "height": 1402,
    "variants": [
      {
        "w": 480,
        "src": "/images/birthday-neon-glow-crazy-480.webp"
      },
      {
        "w": 800,
        "src": "/images/birthday-neon-glow-crazy-800.webp"
      }
    ]
  },
  "/images/birthday-neon-glow-stage.webp": {
    "width": 1122,
    "height": 1402,
    "variants": [
      {
        "w": 480,
        "src": "/images/birthday-neon-glow-stage-480.webp"
      },
      {
        "w": 800,
        "src": "/images/birthday-neon-glow-stage-800.webp"
      }
    ]
  },
  "/images/birthday-pink-floral-stage.webp": {
    "width": 1122,
    "height": 1402,
    "variants": [
      {
        "w": 480,
        "src": "/images/birthday-pink-floral-stage-480.webp"
      },
      {
        "w": 800,
        "src": "/images/birthday-pink-floral-stage-800.webp"
      }
    ]
  },
  "/images/birthday-pink-welcome-board.webp": {
    "width": 1122,
    "height": 1402,
    "variants": [
      {
        "w": 480,
        "src": "/images/birthday-pink-welcome-board-480.webp"
      },
      {
        "w": 800,
        "src": "/images/birthday-pink-welcome-board-800.webp"
      }
    ]
  },
  "/images/birthday-rose-gold-stage.webp": {
    "width": 1122,
    "height": 1402,
    "variants": [
      {
        "w": 480,
        "src": "/images/birthday-rose-gold-stage-480.webp"
      },
      {
        "w": 800,
        "src": "/images/birthday-rose-gold-stage-800.webp"
      }
    ]
  },
  "/images/birthday-rose-gold-welcome.webp": {
    "width": 1086,
    "height": 1448,
    "variants": [
      {
        "w": 480,
        "src": "/images/birthday-rose-gold-welcome-480.webp"
      },
      {
        "w": 800,
        "src": "/images/birthday-rose-gold-welcome-800.webp"
      }
    ]
  },
  "/images/candle-1.webp": {
    "width": 1600,
    "height": 1067,
    "variants": [
      {
        "w": 480,
        "src": "/images/candle-1-480.webp"
      },
      {
        "w": 800,
        "src": "/images/candle-1-800.webp"
      },
      {
        "w": 1200,
        "src": "/images/candle-1-1200.webp"
      }
    ]
  },
  "/images/celebration-1.webp": {
    "width": 1600,
    "height": 1068,
    "variants": [
      {
        "w": 480,
        "src": "/images/celebration-1-480.webp"
      },
      {
        "w": 800,
        "src": "/images/celebration-1-800.webp"
      },
      {
        "w": 1200,
        "src": "/images/celebration-1-1200.webp"
      }
    ]
  },
  "/images/celebration-2.webp": {
    "width": 1600,
    "height": 1068,
    "variants": [
      {
        "w": 480,
        "src": "/images/celebration-2-480.webp"
      },
      {
        "w": 800,
        "src": "/images/celebration-2-800.webp"
      },
      {
        "w": 1200,
        "src": "/images/celebration-2-1200.webp"
      }
    ]
  },
  "/images/ceremony-white-chair-setup.webp": {
    "width": 1122,
    "height": 1402,
    "variants": [
      {
        "w": 480,
        "src": "/images/ceremony-white-chair-setup-480.webp"
      },
      {
        "w": 800,
        "src": "/images/ceremony-white-chair-setup-800.webp"
      }
    ]
  },
  "/images/chef-1.webp": {
    "width": 1600,
    "height": 1067,
    "variants": [
      {
        "w": 480,
        "src": "/images/chef-1-480.webp"
      },
      {
        "w": 800,
        "src": "/images/chef-1-800.webp"
      },
      {
        "w": 1200,
        "src": "/images/chef-1-1200.webp"
      }
    ]
  },
  "/images/corporate-1.webp": {
    "width": 1600,
    "height": 1068,
    "variants": [
      {
        "w": 480,
        "src": "/images/corporate-1-480.webp"
      },
      {
        "w": 800,
        "src": "/images/corporate-1-800.webp"
      },
      {
        "w": 1200,
        "src": "/images/corporate-1-1200.webp"
      }
    ]
  },
  "/images/corporate-2.webp": {
    "width": 1600,
    "height": 1067,
    "variants": [
      {
        "w": 480,
        "src": "/images/corporate-2-480.webp"
      },
      {
        "w": 800,
        "src": "/images/corporate-2-800.webp"
      },
      {
        "w": 1200,
        "src": "/images/corporate-2-1200.webp"
      }
    ]
  },
  "/images/corporate-3.webp": {
    "width": 1600,
    "height": 1143,
    "variants": [
      {
        "w": 480,
        "src": "/images/corporate-3-480.webp"
      },
      {
        "w": 800,
        "src": "/images/corporate-3-800.webp"
      },
      {
        "w": 1200,
        "src": "/images/corporate-3-1200.webp"
      }
    ]
  },
  "/images/corporate-4.webp": {
    "width": 1600,
    "height": 1068,
    "variants": [
      {
        "w": 480,
        "src": "/images/corporate-4-480.webp"
      },
      {
        "w": 800,
        "src": "/images/corporate-4-800.webp"
      },
      {
        "w": 1200,
        "src": "/images/corporate-4-1200.webp"
      }
    ]
  },
  "/images/corporate-golden-gala-stage.webp": {
    "width": 1092,
    "height": 1440,
    "variants": [
      {
        "w": 480,
        "src": "/images/corporate-golden-gala-stage-480.webp"
      },
      {
        "w": 800,
        "src": "/images/corporate-golden-gala-stage-800.webp"
      }
    ]
  },
  "/images/corporate-grand-draped-hall.webp": {
    "width": 1092,
    "height": 1440,
    "variants": [
      {
        "w": 480,
        "src": "/images/corporate-grand-draped-hall-480.webp"
      },
      {
        "w": 800,
        "src": "/images/corporate-grand-draped-hall-800.webp"
      }
    ]
  },
  "/images/couple-1.webp": {
    "width": 1600,
    "height": 1067,
    "variants": [
      {
        "w": 480,
        "src": "/images/couple-1-480.webp"
      },
      {
        "w": 800,
        "src": "/images/couple-1-800.webp"
      },
      {
        "w": 1200,
        "src": "/images/couple-1-1200.webp"
      }
    ]
  },
  "/images/couple-2.webp": {
    "width": 1600,
    "height": 2400,
    "variants": [
      {
        "w": 480,
        "src": "/images/couple-2-480.webp"
      },
      {
        "w": 800,
        "src": "/images/couple-2-800.webp"
      },
      {
        "w": 1200,
        "src": "/images/couple-2-1200.webp"
      }
    ]
  },
  "/images/couple-3.webp": {
    "width": 1600,
    "height": 1067,
    "variants": [
      {
        "w": 480,
        "src": "/images/couple-3-480.webp"
      },
      {
        "w": 800,
        "src": "/images/couple-3-800.webp"
      },
      {
        "w": 1200,
        "src": "/images/couple-3-1200.webp"
      }
    ]
  },
  "/images/couple-indian.webp": {
    "width": 1600,
    "height": 2400,
    "variants": [
      {
        "w": 480,
        "src": "/images/couple-indian-480.webp"
      },
      {
        "w": 800,
        "src": "/images/couple-indian-800.webp"
      },
      {
        "w": 1200,
        "src": "/images/couple-indian-1200.webp"
      }
    ]
  },
  "/images/decor-arch.webp": {
    "width": 1600,
    "height": 1067,
    "variants": [
      {
        "w": 480,
        "src": "/images/decor-arch-480.webp"
      },
      {
        "w": 800,
        "src": "/images/decor-arch-800.webp"
      },
      {
        "w": 1200,
        "src": "/images/decor-arch-1200.webp"
      }
    ]
  },
  "/images/decor-blossom-stage-backdrop.webp": {
    "width": 1200,
    "height": 771,
    "variants": [
      {
        "w": 480,
        "src": "/images/decor-blossom-stage-backdrop-480.webp"
      },
      {
        "w": 800,
        "src": "/images/decor-blossom-stage-backdrop-800.webp"
      }
    ]
  },
  "/images/decor-bouquet.webp": {
    "width": 1600,
    "height": 2400,
    "variants": [
      {
        "w": 480,
        "src": "/images/decor-bouquet-480.webp"
      },
      {
        "w": 800,
        "src": "/images/decor-bouquet-800.webp"
      },
      {
        "w": 1200,
        "src": "/images/decor-bouquet-1200.webp"
      }
    ]
  },
  "/images/decor-ceremony.webp": {
    "width": 1600,
    "height": 1068,
    "variants": [
      {
        "w": 480,
        "src": "/images/decor-ceremony-480.webp"
      },
      {
        "w": 800,
        "src": "/images/decor-ceremony-800.webp"
      },
      {
        "w": 1200,
        "src": "/images/decor-ceremony-1200.webp"
      }
    ]
  },
  "/images/decor-floral-chandelier-backdrop.webp": {
    "width": 1122,
    "height": 1402,
    "variants": [
      {
        "w": 480,
        "src": "/images/decor-floral-chandelier-backdrop-480.webp"
      },
      {
        "w": 800,
        "src": "/images/decor-floral-chandelier-backdrop-800.webp"
      }
    ]
  },
  "/images/decor-floral.webp": {
    "width": 1600,
    "height": 1067,
    "variants": [
      {
        "w": 480,
        "src": "/images/decor-floral-480.webp"
      },
      {
        "w": 800,
        "src": "/images/decor-floral-800.webp"
      },
      {
        "w": 1200,
        "src": "/images/decor-floral-1200.webp"
      }
    ]
  },
  "/images/decor-outdoor.webp": {
    "width": 1600,
    "height": 1065,
    "variants": [
      {
        "w": 480,
        "src": "/images/decor-outdoor-480.webp"
      },
      {
        "w": 800,
        "src": "/images/decor-outdoor-800.webp"
      },
      {
        "w": 1200,
        "src": "/images/decor-outdoor-1200.webp"
      }
    ]
  },
  "/images/decor-pink-floral-tower.webp": {
    "width": 1122,
    "height": 1402,
    "variants": [
      {
        "w": 480,
        "src": "/images/decor-pink-floral-tower-480.webp"
      },
      {
        "w": 800,
        "src": "/images/decor-pink-floral-tower-800.webp"
      }
    ]
  },
  "/images/decor-setting.webp": {
    "width": 1600,
    "height": 1067,
    "variants": [
      {
        "w": 480,
        "src": "/images/decor-setting-480.webp"
      },
      {
        "w": 800,
        "src": "/images/decor-setting-800.webp"
      },
      {
        "w": 1200,
        "src": "/images/decor-setting-1200.webp"
      }
    ]
  },
  "/images/decor-stage.webp": {
    "width": 1600,
    "height": 1067,
    "variants": [
      {
        "w": 480,
        "src": "/images/decor-stage-480.webp"
      },
      {
        "w": 800,
        "src": "/images/decor-stage-800.webp"
      },
      {
        "w": 1200,
        "src": "/images/decor-stage-1200.webp"
      }
    ]
  },
  "/images/decor-table.webp": {
    "width": 1600,
    "height": 1068,
    "variants": [
      {
        "w": 480,
        "src": "/images/decor-table-480.webp"
      },
      {
        "w": 800,
        "src": "/images/decor-table-800.webp"
      },
      {
        "w": 1200,
        "src": "/images/decor-table-1200.webp"
      }
    ]
  },
  "/images/dining-1.webp": {
    "width": 1600,
    "height": 1067,
    "variants": [
      {
        "w": 480,
        "src": "/images/dining-1-480.webp"
      },
      {
        "w": 800,
        "src": "/images/dining-1-800.webp"
      },
      {
        "w": 1200,
        "src": "/images/dining-1-1200.webp"
      }
    ]
  },
  "/images/dining-2.webp": {
    "width": 1600,
    "height": 1067,
    "variants": [
      {
        "w": 480,
        "src": "/images/dining-2-480.webp"
      },
      {
        "w": 800,
        "src": "/images/dining-2-800.webp"
      },
      {
        "w": 1200,
        "src": "/images/dining-2-1200.webp"
      }
    ]
  },
  "/images/dining-3.webp": {
    "width": 1600,
    "height": 1068,
    "variants": [
      {
        "w": 480,
        "src": "/images/dining-3-480.webp"
      },
      {
        "w": 800,
        "src": "/images/dining-3-800.webp"
      },
      {
        "w": 1200,
        "src": "/images/dining-3-1200.webp"
      }
    ]
  },
  "/images/flowers-2.webp": {
    "width": 1600,
    "height": 1600,
    "variants": [
      {
        "w": 480,
        "src": "/images/flowers-2-480.webp"
      },
      {
        "w": 800,
        "src": "/images/flowers-2-800.webp"
      },
      {
        "w": 1200,
        "src": "/images/flowers-2-1200.webp"
      }
    ]
  },
  "/images/flowers-3.webp": {
    "width": 1600,
    "height": 1600,
    "variants": [
      {
        "w": 480,
        "src": "/images/flowers-3-480.webp"
      },
      {
        "w": 800,
        "src": "/images/flowers-3-800.webp"
      },
      {
        "w": 1200,
        "src": "/images/flowers-3-1200.webp"
      }
    ]
  },
  "/images/gift-1.webp": {
    "width": 1600,
    "height": 1106,
    "variants": [
      {
        "w": 480,
        "src": "/images/gift-1-480.webp"
      },
      {
        "w": 800,
        "src": "/images/gift-1-800.webp"
      },
      {
        "w": 1200,
        "src": "/images/gift-1-1200.webp"
      }
    ]
  },
  "/images/gift-2.webp": {
    "width": 1600,
    "height": 1200,
    "variants": [
      {
        "w": 480,
        "src": "/images/gift-2-480.webp"
      },
      {
        "w": 800,
        "src": "/images/gift-2-800.webp"
      },
      {
        "w": 1200,
        "src": "/images/gift-2-1200.webp"
      }
    ]
  },
  "/images/gift-3.webp": {
    "width": 1600,
    "height": 1067,
    "variants": [
      {
        "w": 480,
        "src": "/images/gift-3-480.webp"
      },
      {
        "w": 800,
        "src": "/images/gift-3-800.webp"
      },
      {
        "w": 1200,
        "src": "/images/gift-3-1200.webp"
      }
    ]
  },
  "/images/hero.webp": {
    "width": 1600,
    "height": 1034,
    "variants": [
      {
        "w": 480,
        "src": "/images/hero-480.webp"
      },
      {
        "w": 800,
        "src": "/images/hero-800.webp"
      },
      {
        "w": 1200,
        "src": "/images/hero-1200.webp"
      }
    ]
  },
  "/images/light-1.webp": {
    "width": 1600,
    "height": 1067,
    "variants": [
      {
        "w": 480,
        "src": "/images/light-1-480.webp"
      },
      {
        "w": 800,
        "src": "/images/light-1-800.webp"
      },
      {
        "w": 1200,
        "src": "/images/light-1-1200.webp"
      }
    ]
  },
  "/images/wedding-floral-stage-loveseat.webp": {
    "width": 1122,
    "height": 1402,
    "variants": [
      {
        "w": 480,
        "src": "/images/wedding-floral-stage-loveseat-480.webp"
      },
      {
        "w": 800,
        "src": "/images/wedding-floral-stage-loveseat-800.webp"
      }
    ]
  },
  "/images/wedding-pink-floral-stage.webp": {
    "width": 1200,
    "height": 800,
    "variants": [
      {
        "w": 480,
        "src": "/images/wedding-pink-floral-stage-480.webp"
      },
      {
        "w": 800,
        "src": "/images/wedding-pink-floral-stage-800.webp"
      }
    ]
  }
} as const;
