/**
 * AUTO-GENERATED by scripts/optimize-images.mjs — do not edit by hand.
 * Run `npm run images` after adding or replacing photography.
 *
 * Maps each source image to its re-encoded WebP variants so components can
 * build an accurate `srcset` without hardcoding breakpoints.
 */

import type { ImageManifest } from "@/data/images";

export const imageManifest: ImageManifest = {
  "/images/banquet-1.webp": {
    "width": 1600,
    "height": 1067,
    "variants": [
      {
        "w": 480,
        "src": "/images/banquet-1-480.webp"
      },
      {
        "w": 800,
        "src": "/images/banquet-1-800.webp"
      },
      {
        "w": 1200,
        "src": "/images/banquet-1-1200.webp"
      }
    ]
  },
  "/images/banquet-2.webp": {
    "width": 1600,
    "height": 1067,
    "variants": [
      {
        "w": 480,
        "src": "/images/banquet-2-480.webp"
      },
      {
        "w": 800,
        "src": "/images/banquet-2-800.webp"
      },
      {
        "w": 1200,
        "src": "/images/banquet-2-1200.webp"
      }
    ]
  },
  "/images/candle-1.webp": {
    "width": 1600,
    "height": 1067,
    "variants": [
      {
        "w": 480,
        "src": "/images/candle-1-480.webp"
      },
      {
        "w": 800,
        "src": "/images/candle-1-800.webp"
      },
      {
        "w": 1200,
        "src": "/images/candle-1-1200.webp"
      }
    ]
  },
  "/images/celebration-1.webp": {
    "width": 1600,
    "height": 1068,
    "variants": [
      {
        "w": 480,
        "src": "/images/celebration-1-480.webp"
      },
      {
        "w": 800,
        "src": "/images/celebration-1-800.webp"
      },
      {
        "w": 1200,
        "src": "/images/celebration-1-1200.webp"
      }
    ]
  },
  "/images/celebration-2.webp": {
    "width": 1600,
    "height": 1068,
    "variants": [
      {
        "w": 480,
        "src": "/images/celebration-2-480.webp"
      },
      {
        "w": 800,
        "src": "/images/celebration-2-800.webp"
      },
      {
        "w": 1200,
        "src": "/images/celebration-2-1200.webp"
      }
    ]
  },
  "/images/chef-1.webp": {
    "width": 1600,
    "height": 1067,
    "variants": [
      {
        "w": 480,
        "src": "/images/chef-1-480.webp"
      },
      {
        "w": 800,
        "src": "/images/chef-1-800.webp"
      },
      {
        "w": 1200,
        "src": "/images/chef-1-1200.webp"
      }
    ]
  },
  "/images/corporate-1.webp": {
    "width": 1600,
    "height": 1068,
    "variants": [
      {
        "w": 480,
        "src": "/images/corporate-1-480.webp"
      },
      {
        "w": 800,
        "src": "/images/corporate-1-800.webp"
      },
      {
        "w": 1200,
        "src": "/images/corporate-1-1200.webp"
      }
    ]
  },
  "/images/corporate-2.webp": {
    "width": 1600,
    "height": 1067,
    "variants": [
      {
        "w": 480,
        "src": "/images/corporate-2-480.webp"
      },
      {
        "w": 800,
        "src": "/images/corporate-2-800.webp"
      },
      {
        "w": 1200,
        "src": "/images/corporate-2-1200.webp"
      }
    ]
  },
  "/images/corporate-3.webp": {
    "width": 1600,
    "height": 1143,
    "variants": [
      {
        "w": 480,
        "src": "/images/corporate-3-480.webp"
      },
      {
        "w": 800,
        "src": "/images/corporate-3-800.webp"
      },
      {
        "w": 1200,
        "src": "/images/corporate-3-1200.webp"
      }
    ]
  },
  "/images/corporate-4.webp": {
    "width": 1600,
    "height": 1068,
    "variants": [
      {
        "w": 480,
        "src": "/images/corporate-4-480.webp"
      },
      {
        "w": 800,
        "src": "/images/corporate-4-800.webp"
      },
      {
        "w": 1200,
        "src": "/images/corporate-4-1200.webp"
      }
    ]
  },
  "/images/couple-1.webp": {
    "width": 1600,
    "height": 1067,
    "variants": [
      {
        "w": 480,
        "src": "/images/couple-1-480.webp"
      },
      {
        "w": 800,
        "src": "/images/couple-1-800.webp"
      },
      {
        "w": 1200,
        "src": "/images/couple-1-1200.webp"
      }
    ]
  },
  "/images/couple-2.webp": {
    "width": 1600,
    "height": 2400,
    "variants": [
      {
        "w": 480,
        "src": "/images/couple-2-480.webp"
      },
      {
        "w": 800,
        "src": "/images/couple-2-800.webp"
      },
      {
        "w": 1200,
        "src": "/images/couple-2-1200.webp"
      }
    ]
  },
  "/images/couple-3.webp": {
    "width": 1600,
    "height": 1067,
    "variants": [
      {
        "w": 480,
        "src": "/images/couple-3-480.webp"
      },
      {
        "w": 800,
        "src": "/images/couple-3-800.webp"
      },
      {
        "w": 1200,
        "src": "/images/couple-3-1200.webp"
      }
    ]
  },
  "/images/couple-indian.webp": {
    "width": 1600,
    "height": 2400,
    "variants": [
      {
        "w": 480,
        "src": "/images/couple-indian-480.webp"
      },
      {
        "w": 800,
        "src": "/images/couple-indian-800.webp"
      },
      {
        "w": 1200,
        "src": "/images/couple-indian-1200.webp"
      }
    ]
  },
  "/images/decor-arch.webp": {
    "width": 1600,
    "height": 1067,
    "variants": [
      {
        "w": 480,
        "src": "/images/decor-arch-480.webp"
      },
      {
        "w": 800,
        "src": "/images/decor-arch-800.webp"
      },
      {
        "w": 1200,
        "src": "/images/decor-arch-1200.webp"
      }
    ]
  },
  "/images/decor-bouquet.webp": {
    "width": 1600,
    "height": 2400,
    "variants": [
      {
        "w": 480,
        "src": "/images/decor-bouquet-480.webp"
      },
      {
        "w": 800,
        "src": "/images/decor-bouquet-800.webp"
      },
      {
        "w": 1200,
        "src": "/images/decor-bouquet-1200.webp"
      }
    ]
  },
  "/images/decor-ceremony.webp": {
    "width": 1600,
    "height": 1068,
    "variants": [
      {
        "w": 480,
        "src": "/images/decor-ceremony-480.webp"
      },
      {
        "w": 800,
        "src": "/images/decor-ceremony-800.webp"
      },
      {
        "w": 1200,
        "src": "/images/decor-ceremony-1200.webp"
      }
    ]
  },
  "/images/decor-floral.webp": {
    "width": 1600,
    "height": 1067,
    "variants": [
      {
        "w": 480,
        "src": "/images/decor-floral-480.webp"
      },
      {
        "w": 800,
        "src": "/images/decor-floral-800.webp"
      },
      {
        "w": 1200,
        "src": "/images/decor-floral-1200.webp"
      }
    ]
  },
  "/images/decor-outdoor.webp": {
    "width": 1600,
    "height": 1065,
    "variants": [
      {
        "w": 480,
        "src": "/images/decor-outdoor-480.webp"
      },
      {
        "w": 800,
        "src": "/images/decor-outdoor-800.webp"
      },
      {
        "w": 1200,
        "src": "/images/decor-outdoor-1200.webp"
      }
    ]
  },
  "/images/decor-setting.webp": {
    "width": 1600,
    "height": 1067,
    "variants": [
      {
        "w": 480,
        "src": "/images/decor-setting-480.webp"
      },
      {
        "w": 800,
        "src": "/images/decor-setting-800.webp"
      },
      {
        "w": 1200,
        "src": "/images/decor-setting-1200.webp"
      }
    ]
  },
  "/images/decor-stage.webp": {
    "width": 1600,
    "height": 1067,
    "variants": [
      {
        "w": 480,
        "src": "/images/decor-stage-480.webp"
      },
      {
        "w": 800,
        "src": "/images/decor-stage-800.webp"
      },
      {
        "w": 1200,
        "src": "/images/decor-stage-1200.webp"
      }
    ]
  },
  "/images/decor-table.webp": {
    "width": 1600,
    "height": 1068,
    "variants": [
      {
        "w": 480,
        "src": "/images/decor-table-480.webp"
      },
      {
        "w": 800,
        "src": "/images/decor-table-800.webp"
      },
      {
        "w": 1200,
        "src": "/images/decor-table-1200.webp"
      }
    ]
  },
  "/images/dining-1.webp": {
    "width": 1600,
    "height": 1067,
    "variants": [
      {
        "w": 480,
        "src": "/images/dining-1-480.webp"
      },
      {
        "w": 800,
        "src": "/images/dining-1-800.webp"
      },
      {
        "w": 1200,
        "src": "/images/dining-1-1200.webp"
      }
    ]
  },
  "/images/dining-2.webp": {
    "width": 1600,
    "height": 1067,
    "variants": [
      {
        "w": 480,
        "src": "/images/dining-2-480.webp"
      },
      {
        "w": 800,
        "src": "/images/dining-2-800.webp"
      },
      {
        "w": 1200,
        "src": "/images/dining-2-1200.webp"
      }
    ]
  },
  "/images/dining-3.webp": {
    "width": 1600,
    "height": 1068,
    "variants": [
      {
        "w": 480,
        "src": "/images/dining-3-480.webp"
      },
      {
        "w": 800,
        "src": "/images/dining-3-800.webp"
      },
      {
        "w": 1200,
        "src": "/images/dining-3-1200.webp"
      }
    ]
  },
  "/images/flowers-2.webp": {
    "width": 1600,
    "height": 1600,
    "variants": [
      {
        "w": 480,
        "src": "/images/flowers-2-480.webp"
      },
      {
        "w": 800,
        "src": "/images/flowers-2-800.webp"
      },
      {
        "w": 1200,
        "src": "/images/flowers-2-1200.webp"
      }
    ]
  },
  "/images/flowers-3.webp": {
    "width": 1600,
    "height": 1600,
    "variants": [
      {
        "w": 480,
        "src": "/images/flowers-3-480.webp"
      },
      {
        "w": 800,
        "src": "/images/flowers-3-800.webp"
      },
      {
        "w": 1200,
        "src": "/images/flowers-3-1200.webp"
      }
    ]
  },
  "/images/gift-1.webp": {
    "width": 1600,
    "height": 1106,
    "variants": [
      {
        "w": 480,
        "src": "/images/gift-1-480.webp"
      },
      {
        "w": 800,
        "src": "/images/gift-1-800.webp"
      },
      {
        "w": 1200,
        "src": "/images/gift-1-1200.webp"
      }
    ]
  },
  "/images/gift-2.webp": {
    "width": 1600,
    "height": 1200,
    "variants": [
      {
        "w": 480,
        "src": "/images/gift-2-480.webp"
      },
      {
        "w": 800,
        "src": "/images/gift-2-800.webp"
      },
      {
        "w": 1200,
        "src": "/images/gift-2-1200.webp"
      }
    ]
  },
  "/images/gift-3.webp": {
    "width": 1600,
    "height": 1067,
    "variants": [
      {
        "w": 480,
        "src": "/images/gift-3-480.webp"
      },
      {
        "w": 800,
        "src": "/images/gift-3-800.webp"
      },
      {
        "w": 1200,
        "src": "/images/gift-3-1200.webp"
      }
    ]
  },
  "/images/hero.webp": {
    "width": 1600,
    "height": 1034,
    "variants": [
      {
        "w": 480,
        "src": "/images/hero-480.webp"
      },
      {
        "w": 800,
        "src": "/images/hero-800.webp"
      },
      {
        "w": 1200,
        "src": "/images/hero-1200.webp"
      }
    ]
  },
  "/images/light-1.webp": {
    "width": 1600,
    "height": 1067,
    "variants": [
      {
        "w": 480,
        "src": "/images/light-1-480.webp"
      },
      {
        "w": 800,
        "src": "/images/light-1-800.webp"
      },
      {
        "w": 1200,
        "src": "/images/light-1-1200.webp"
      }
    ]
  }
} as const;
